use_frameworks!

platform :ios, '9.0'

target 'SDWebImageWebPCoder_Example' do
  pod 'SDWebImageWebPCoder', :path => '../'

  target 'SDWebImageWebPCoder_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
